### PR TITLE
Control sizes of large images

### PR DESCRIPTION
**Pull request by buberdds**
#143 

Options:
1) use official `plugin-ideal-image` to control large images
    - plugin is not bundled into `@docusaurus/preset-classic` preset like most of other official plugins
    - renaming to `.mdx` is not necessary, but might be good for third-party tools according to docs

2) manually replace images in repo and don't add `plugin-ideal-image`

3) Any other ideas?

* `6b_ledger_oasis_ready` does not need resizing. Switching to jpg is enough.

### CODE REVIEW

**Comment by matevz** [comment]
Nice catch. Can you also reformat the rest of the images in this PR accordingly and/or find substitutes?

**Comment by lukaw3d** [comment]
@matevz do you know if we have svg sources of e.g. https://github.com/oasisprotocol/docs/blob/main/docs/oasis-network-primer/images/Group_8.png

**Comment by lukaw3d** [comment]
> option 2: manually replace images in repo and don't add plugin-ideal-image

I would prefer this, but sadly it won't reduce the repo size without rewriting history :/

**Comment by lukaw3d** [comment]
Tried to optimize with https://squoosh.app/. docs/docs folder size: 43.9 MB -> 13.1 MB

Seems like jpgs lost some vibrancy.

**Comment by buberdds** [comment]
Thanks for sharing, never heard about it before. Will explore options with resizing now.

**Review by lukaw3d — APPROVED** [review]

**Comment by matevz** [comment]
Why did image brightness change? e.g. https://github.com/oasisprotocol/docs/pull/146/files#diff-c8ac17fbe04959322612fa9ece20f8c658da0ab93ce11bf35368b8d505a8ddb5

I think screenshots should be as they are. Lossless compression and resolution reduction from highdpi desktops are ok, but not changing colors/brightness.

**Review by matevz — APPROVED** [review]
Good work. Just check why the brightness of some images changed.

**Comment by tjanez** [comment]
> but not changing colors/brightness.

I wouldn't worry about brightness too much currently.

Let's rather make sure we have a process that will prevent uploading PNG images that can't be compressed well.

**Review by tjanez — APPROVED** [review]
Thanks, @buberdds!

**Comment by tjanez** [comment]
Follow up issues: #153 and #154.

**Comment by lukaw3d** [comment]
Fixed colors by converting from "DELL U3818DW" color profile to "sRGB" and then removing it
`convert "$i" -profile /usr/share/color/icc/colord/sRGB.icc -strip`

**Comment by tjanez** [comment]
> Fixed colors by converting from "DELL U3818DW" color profile to "sRGB" and then removing it
> `convert "$i" -profile /usr/share/color/icc/colord/sRGB.icc -strip`

Nice :slightly_smiling_face:

**Pull request merged**
