### PR TITLE
submodules: Switch external/oasis-core to stable/22.2.x branch

### PR DESCRIPTION
**Pull request by tjanez**

### CODE REVIEW

**Comment by matevz** [comment]
This should be updated:
https://github.com/oasisprotocol/docs/blob/tjanez/oasis-core-stable/src/editUrl.js#L7

to 

```
    'external/oasis-core/': 'https://github.com/oasisprotocol/oasis-core/{mode}/stable/22.2.x/',
```

**Comment by tjanez** [comment]
> This should be updated: https://github.com/oasisprotocol/docs/blob/tjanez/oasis-core-stable/src/editUrl.js#L7
> 
> to
> 
> ```
>     'external/oasis-core/': 'https://github.com/oasisprotocol/oasis-core/{mode}/stable/22.2.x/',
> ```

Thanks! Done.

**Review by matevz — APPROVED** [review]
I suggest we first merge https://github.com/oasisprotocol/oasis-core/pull/5073 into stable/22.2.x branch and then bump the `external/oasis-core`. Otherwise LGTM.

**Comment by tjanez** [comment]
> I suggest we first merge [oasisprotocol/oasis-core#5073](https://github.com/oasisprotocol/oasis-core/pull/5073) into stable/22.2.x branch and then bump the `external/oasis-core`. Otherwise LGTM.

Agreed, done.

**Pull request merged**
